version: '3'

services:
  raspberry_pi_os:
    #image: resin/rpi-raspbian
    image: balenalib/raspberrypi3
    container_name: raspberry_pi_os_container
    privileged: true
    restart: unless-stopped
    stdin_open: true
    tty: true

#docker-compose -d -f ./docker-compose.yml up