port:
  8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/c2110i?useSSL=false&serverTimezone=UTC
    username: root
    password: Abc123456789@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: mysql
