version: "3.9"
services:
  php:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    container_name: php-container
    ports:
      - "8083:5000"
    volumes:
      - .:/code
    networks:
      - backend
    depends_on:
      - mysql
  mysql:
    image: "mysql:8.0.30"
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Abc123456789
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
    name: php-mysql-backend
###

###
# docker compose -f ./docker-compose.yml up