#server.port=8081
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/de01
#spring.datasource.username=root
#spring.datasource.password=
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.properties.hibernate.format_sql=true
#spring.datasource.driver-class-name =com.mysql.cj.jdbc.Driver
#spring.mvc.view.prefix=/views/
#spring.mvc.view.suffix=.jsp



server:
  port: 8082
  include-message: always
  include-binding-errors: always
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    username: root
    password:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/de01
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    properties:
      format_sql: true
      hibernate:
        generate-ddl: true
        show_sql: true
        use_sql_comments: true
        format_sql: true
        ddl-auto: update
